name: Serverless Branch Deployment Cleanup
on:
  pull_request:
    types: [closed]
jobs:
  s3_bucket_cleanup:
    name: S3 Cleanup after branch deploy PR close
    if: github.event.action == 'closed'
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::872515293554:role/gha-branch-deploys-s3
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: eu-west-2
      - name: Clean up S3 on close or merge
        run: |
          aws s3 rm s3://weave.energy-branches/ --recursive --exclude "*" --include "$GITHUB_HEAD_REF*"
